version: 1.0
mode: prod

# место храненния кэшей, начинается с App::$webRoot
cache: _cache/
memcache: include(memcache.yaml)

# всякие настройки
settings: include(settings.yaml)

# базы данных, подключения
databases: include(databases.yaml)

# список доменов
hosts: include(hosts.yaml)

# настройки логгера
logger: include(logger.yaml)

# список модулей
modules: include(modules.yaml)  