domains:
  manage: 
    - "backend.carrier-gate.com"
  carrier-gate:
    - "*_gate.local.bsft.loc"
services:
  vault: "vault.colibrilab.ru"
  fs: "fs.colibrilab.ru"
  tpl: "templates.colibrilab.ru"
  print: "printsrv.colibrilab.ru"