version: "1.0"
mode: local

# место храненния кэшей, начинается с App::$webRoot
cache: _cache/
res: files/
memcache: include(memcache.yaml)
monitoring:
  logging: 0 # 0 - EveryTimer, 1 - FullStackOnly, 2 - Never
  level: 7 # Logger::*

# всякие настройки
settings: include(settings.yaml)

# базы данных, подключения
databases: include(databases.yaml)

# список доменов
hosts: include(hosts.yaml)

# настройки логгера
logger: include(logger.yaml)

# список модулей
modules: include(modules.yaml)  

comet: include(comet.yaml)

mobile: include(mobile.yaml)

minifier: include(minifier.yaml)