domains:
  manage: 
    - "cblank.local.bsft.loc"
    - "localhost"
  pocket: 
    - "pocket.local.bsft.loc"
    - "www.pocket.local.bsft.loc"
  commerce: 
    - "commerce.local.bsft.loc"
    - "www.commerce.local.bsft.loc"
  test:
    - "test.local.bsft.loc"
services:
  fs: "fs.local.bsft.loc"
  tpl: "templates.local.bsft.loc"
  print: "printsrv.local.bsft.loc"